<a href="https://colab.research.google.com/github/rtarun1/pytorch-01/blob/main/CS231n_%5BA1%5D.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch
print(torch. __version__)

2.3.0+cu121


In [3]:
for i in range(3):
  print(i)


0
1
2


In [7]:
#one dimentional tensor
a  = torch.tensor([1, 2, 3])
print("Here is a: ", a)
print('type of a:', type(a))
print('dimention of a ', a.dim())
print('a.shape:', a.shape)
print(type(a[0].item()))

a[1] = 10
print(a)

Here is a:  tensor([1, 2, 3])
type of a: <class 'torch.Tensor'>
dimention of a  1
a.shape: torch.Size([3])
<class 'int'>
tensor([ 1, 10,  3])


In [15]:
#two-dimentional tensor
b = torch.tensor([[1, 2, 3], [4, 5, 6]])
print(b)
print(b.shape)
print(b[0,1], b[1,2])
b[1, 1] = 100
print(b)

tensor([[1, 2, 3],
        [4, 5, 6]])
torch.Size([2, 3])
tensor(2) tensor(6)
tensor([[  1,   2,   3],
        [  4, 100,   6]])


In [26]:
c = torch.tensor([[0,0],[0,0],[0,0]])
print(c.shape)
print(c)

c[0, 1] = 10
c[1, 0] = 100
print(c)

torch.Size([3, 2])
tensor([[0, 0],
        [0, 0],
        [0, 0]])
tensor([[  0,  10],
        [100,   0],
        [  0,   0]])
