<a href="https://colab.research.google.com/github/rtarun1/pytorch-01/blob/main/pytorch_01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
import numpy as np


In [ ]:
np1 = np.random.rand(2,2)
np1

array([[0.59899085, 0.97964126],
       [0.88719192, 0.48436087]])

In [ ]:
tensor_2d = torch.randn(2,2)
tensor_2d

tensor([[1.0055, 0.6710],
        [0.1408, 2.0668]])

In [ ]:
tensor_2d.dtype

torch.float32

In [ ]:
tensor_3d = torch.randn(4,2,3)
tensor_3d

tensor([[[ 1.1194,  1.1733,  0.8482],
         [-0.8999,  0.6200,  1.4208]],

        [[ 0.3845, -0.2300, -0.3309],
         [ 0.3893,  0.0645, -0.4026]],

        [[ 0.8915,  0.2376,  0.5187],
         [-0.8535, -0.1726, -0.0082]],

        [[ 1.3905, -0.6999, -0.9359],
         [-1.5596,  0.1993, -1.1753]]])

In [ ]:
## lets make the numpy array to tensor

my_tensor = torch.tensor(np1)
my_tensor

tensor([[0.5990, 0.9796],
        [0.8872, 0.4844]], dtype=torch.float64)

# Tensor Operations


In [ ]:
my_torch = torch.arange(10)
my_torch

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
##Reshape and view
my_torch = my_torch.reshape(5,-1)
my_torch


tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])

In [ ]:
my_torch2 = torch.arange(10)
my_torch2

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
my_torch3 = my_torch2.reshape(2,-1)
my_torch3

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [ ]:
my_torch2[1] = 221
my_torch3

tensor([[  0, 221,   2,   3,   4],
        [  5,   6,   7,   8,   9]])